### ISSUE TITLE
can't get pages from getSingleShelf

### ISSUE THREAD

**Issue by m52go** [bdickason/node-goodreads#34]
i'm trying to use `getSingleShelf` to get a list of all a user's books. the first call i make works fine, no matter which page i request. every subsequent call fails.

what i've tried: 1) spacing calls out by a second or more (in case there's some per-second rate limit on api calls), 2) re-initializing the client variable (see commented code inside setTimeout below).

    var instance = new gr.client({ 'key': 'blah', 'secret': 'blah' });
    var shelfOptions = { 'userID': u.profile.gr_profile.userid, 'shelf': '', 'page': 1, 'per_page': 10, 'accessToken': u.profile.gr_profile.accessToken, 'accessTokenSecret': u.profile.gr_profile.accessTokenSecret };

	for( var i = 1; i <= 3; i++ ) {
	  setTimeout( function(x) { 
	    return function() { 
	    	shelfOptions.page = x;
                
            //re-initializing not working
	    	//instance = new gr.client({ 'key': 'blah', 'secret': 'blah' });
	    	
	    	instance.getSingleShelf( shelfOptions, function( r ) {
		    console.log( r );
		});
	        
	    };
	  }(i), 1000*i);    //waiting to make calls not working
	}

any idea what i'm missing?

**Comment by rharriso** [comment]
Try constructing the shelf options inside of the `setTimeoutCallback`

**Comment by m52go** [comment]
OMG THAT WORKED. but why? it's just an ordinary object...never thought it should matter where it's constructed.

**Comment by rharriso** [comment]
Creating inside of the loop gives you multiple instances of the options (rather than a single instance). so when you pass the `shelfOptions` to `getSingleShelf`, the values  out from the function, aren't changed out from under the function. 

If you look at the source, the options object gets mutated. https://github.com/bdickason/node-goodreads/blob/master/lib/goodreads/goodreads.js#L109

Also, you are mutating the options in your code, so it is best to have different objects for those.

**Comment by rharriso** [comment]
Does that make sense?

**Comment by m52go** [comment]
yes, that makes perfect sense! thanks for explaining.
